//************************************************************************************************
//
// CCL Binary to C++ Tool
//
// This file is part of Crystal Class Library (R)
// Copyright (c) 2025 CCL Software Licensing GmbH.
// All Rights Reserved.
//
// Licensed for use under either:
//  1. a Commercial License provided by CCL Software Licensing GmbH, or
//  2. GNU Affero General Public License v3.0 (AGPLv3).
// 
// You must choose and comply with one of the above licensing options.
// For more information, please visit ccl.dev.
//
// Filename    : makebin.cpp
// Description : CCL Binary to C++ Tool
//
//************************************************************************************************

#include "appversion.h"

#include "ccl/main/cclargs.h"

#include "ccl/extras/tools/toolhelp.h"

#include "ccl/base/storage/file.h"
#include "ccl/base/storage/textfile.h"

#include "ccl/public/base/memorystream.h"
#include "ccl/public/system/iconsole.h"
#include "ccl/public/systemservices.h"

using namespace CCL;

//////////////////////////////////////////////////////////////////////////////////////////////////
// ccl_main
//////////////////////////////////////////////////////////////////////////////////////////////////

int ccl_main (ArgsRef args)
{
	System::IConsole& console = System::GetConsole ();

	if(args.count () < 4)
	{
		console.writeLine (APP_FULL_NAME ", " APP_COPYRIGHT);

		static CStringPtr usage = "Usage:\n\t" APP_ID " inPath outPath arrayName";

		console.writeLine (usage);
		return -1;
	}

	Url inPath, outPath;
	CommandLineTool ().makeAbsolute (inPath, args[1]);
	CommandLineTool ().makeAbsolute (outPath, args[2]);
	String arrayName (args[3]);

	AutoPtr<IMemoryStream> dataStream = File::loadBinaryFile (inPath);
	if(dataStream == nullptr)
		return -1;

	TextFile sourceFile (outPath, Text::kASCII);
	if(!sourceFile.isValid ())
		return -1;

	uint32 size = dataStream->getBytesWritten ();
	uint8* data = (uint8*)dataStream->getMemoryAddress ();

	String fileName;
	inPath.getName (fileName);
	sourceFile->writeString (String () << "// Generated by " APP_NAME " from " << fileName << ":", true);
	sourceFile->writeNewline ();
	sourceFile->writeString (String () << "static const unsigned char " << arrayName << "_Data[" << (int)size << "] =", true);
	sourceFile->writeString ("{", true);

	const int kAlign = 16;
	String line ("\t");
	for(uint32 i = 0; i < size-1; i++)
	{
		if(i > 0 && (i % kAlign) == 0)
		{
			sourceFile->writeString (line, true);
			line = "\t";
		}

		line << "0x";
		line.appendHexValue (data[i], 2);
		line << ", ";
	}

	line << "0x";
	line.appendHexValue (data[size-1], 2);
	sourceFile->writeString (line, true);
	sourceFile->writeString (String () << "};", true);
	sourceFile->writeNewline ();
	sourceFile->writeString (String () << "unsigned int " << arrayName << "_Size = " << (int)size << ";", true);
	sourceFile->writeString (String () << "void* " << arrayName << "_Ptr = (void*)" << arrayName << "_Data;", true);

	return 0;
}
