//************************************************************************************************
//
// This file is part of Crystal Class Library (R)
// Copyright (c) 2025 CCL Software Licensing GmbH.
// All Rights Reserved.
//
// Licensed for use under either:
//  1. a Commercial License provided by CCL Software Licensing GmbH, or
//  2. GNU Affero General Public License v3.0 (AGPLv3).
// 
// You must choose and comply with one of the above licensing options.
// For more information, please visit ccl.dev.
//
// Filename    : core/platform/corefeatures.h
// Description : Feature definitions
//
//************************************************************************************************

#ifndef _corefeatures_h
#define _corefeatures_h

#include "core/public/coreplatform.h"
#include "core/public/coremacros.h"

//////////////////////////////////////////////////////////////////////////////////////////////////
// Implementation API definitions
//////////////////////////////////////////////////////////////////////////////////////////////////

#define CORE_FEATURE_UNIMPLEMENTED				-1 //< Feature not implemented
#define CORE_PLATFORM_IMPLEMENTATION			0 //< Platform-specific implementation
#define CORE_EXTERNAL_PLATFORM_IMPLEMENTATION	1 //< Platform-specific implementation in external directory
#define CORE_FEATURE_IMPLEMENTATION_POSIX		2 //< Portable Operating System Interface
#define CORE_FEATURE_IMPLEMENTATION_CMSIS		3 //< Cortex Microcontroller Software Interface Standard
#define CORE_FEATURE_IMPLEMENTATION_LWIP		4 //< Lightweight IP
#define CORE_FEATURE_IMPLEMENTATION_OPENSSL		5 //< OpenSSL

//////////////////////////////////////////////////////////////////////////////////////////////////
// Core Features
//////////////////////////////////////////////////////////////////////////////////////////////////

/*
* All features default to platform-specific implementation.
* Specify feature implementations where appropriate.
*/

#if CORE_PLATFORM_WINDOWS

	#define CORE_PLATFORM_DIRECTORY win

#elif CORE_PLATFORM_MAC

	#define CORE_PLATFORM_DIRECTORY cocoa
	#define CORE_DISCOVERY_IMPLEMENTATION		CORE_FEATURE_IMPLEMENTATION_POSIX
	#define CORE_INTERPROCESS_IMPLEMENTATION	CORE_FEATURE_IMPLEMENTATION_POSIX

#elif CORE_PLATFORM_IOS

	#define CORE_PLATFORM_DIRECTORY cocoa
	#define CORE_DISCOVERY_IMPLEMENTATION		CORE_FEATURE_IMPLEMENTATION_POSIX
	#define CORE_INTERPROCESS_IMPLEMENTATION	CORE_FEATURE_IMPLEMENTATION_POSIX
	
#elif CORE_PLATFORM_ANDROID

	#define CORE_PLATFORM_DIRECTORY android
	#define CORE_TIME_IMPLEMENTATION			CORE_FEATURE_IMPLEMENTATION_POSIX
	#define CORE_ATOMIC_IMPLEMENTATION			CORE_FEATURE_IMPLEMENTATION_POSIX
	#define CORE_NETWORK_IMPLEMENTATION			CORE_FEATURE_IMPLEMENTATION_POSIX
	#define CORE_ATOMIC_STACK_IMPLEMENTATION	CORE_FEATURE_IMPLEMENTATION_POSIX
	#define CORE_DYNAMICLIBRARY_IMPLEMENTATION	CORE_FEATURE_UNIMPLEMENTED

#elif CORE_PLATFORM_LINUX

	#define CORE_PLATFORM_DIRECTORY linux
	#define CORE_TIME_IMPLEMENTATION			CORE_FEATURE_IMPLEMENTATION_POSIX
	#define CORE_ATOMIC_IMPLEMENTATION			CORE_FEATURE_IMPLEMENTATION_POSIX
	#define CORE_NETWORK_IMPLEMENTATION			CORE_FEATURE_IMPLEMENTATION_POSIX
#if CORE_USE_OPENSSL
	#define CORE_SSL_IMPLEMENTATION				CORE_FEATURE_IMPLEMENTATION_OPENSSL
#else
	#define CORE_SSL_IMPLEMENTATION				CORE_FEATURE_UNIMPLEMENTED
#endif
	#define CORE_ATOMIC_STACK_IMPLEMENTATION	CORE_FEATURE_IMPLEMENTATION_POSIX
	#define CORE_SOCKET_IMPLEMENTATION			CORE_FEATURE_IMPLEMENTATION_POSIX
	#define CORE_DISCOVERY_IMPLEMENTATION		CORE_FEATURE_IMPLEMENTATION_POSIX
	#define CORE_DYNAMICLIBRARY_IMPLEMENTATION	CORE_FEATURE_IMPLEMENTATION_POSIX
	#define CORE_FILESYSTEM_IMPLEMENTATION		CORE_FEATURE_IMPLEMENTATION_POSIX
	#define CORE_DEBUG_IMPLEMENTATION			CORE_FEATURE_IMPLEMENTATION_POSIX

#elif DSP_TI32

	#define CORE_PLATFORM_DIRECTORY dspti32
	#define CORE_THREAD_IMPLEMENTATION			CORE_FEATURE_UNIMPLEMENTED
	#define CORE_SSL_IMPLEMENTATION				CORE_FEATURE_UNIMPLEMENTED
	#define CORE_ATOMIC_STACK_IMPLEMENTATION	CORE_FEATURE_UNIMPLEMENTED
	#define CORE_DISCOVERY_IMPLEMENTATION		CORE_FEATURE_UNIMPLEMENTED
	#define CORE_DYNAMICLIBRARY_IMPLEMENTATION	CORE_FEATURE_UNIMPLEMENTED
	#define CORE_FILESYSTEM_IMPLEMENTATION		CORE_FEATURE_UNIMPLEMENTED

#elif ARM_TI32

	#define CORE_PLATFORM_DIRECTORY armti32
	#define CORE_TIME_IMPLEMENTATION			CORE_FEATURE_IMPLEMENTATION_POSIX
	#define CORE_THREAD_IMPLEMENTATION			CORE_FEATURE_IMPLEMENTATION_POSIX
	#define CORE_ATOMIC_IMPLEMENTATION			CORE_FEATURE_UNIMPLEMENTED // no atomics for armv5
	#define CORE_SSL_IMPLEMENTATION				CORE_FEATURE_UNIMPLEMENTED
	#define CORE_NETWORK_IMPLEMENTATION			CORE_FEATURE_IMPLEMENTATION_POSIX
	#define CORE_ATOMIC_STACK_IMPLEMENTATION	CORE_FEATURE_UNIMPLEMENTED
	#define CORE_DISCOVERY_IMPLEMENTATION		CORE_FEATURE_IMPLEMENTATION_POSIX
	#define CORE_INTERPROCESS_IMPLEMENTATION	CORE_FEATURE_IMPLEMENTATION_POSIX
	#define CORE_DYNAMICLIBRARY_IMPLEMENTATION	CORE_FEATURE_IMPLEMENTATION_POSIX
	#define CORE_FILESYSTEM_IMPLEMENTATION		CORE_FEATURE_IMPLEMENTATION_POSIX
	#define CORE_DEBUG_IMPLEMENTATION			CORE_FEATURE_IMPLEMENTATION_POSIX

#elif DSP_SHARC

	#define CORE_PLATFORM_DIRECTORY sharc
	#define CORE_SSL_IMPLEMENTATION				CORE_FEATURE_UNIMPLEMENTED
	#define CORE_ATOMIC_STACK_IMPLEMENTATION	CORE_FEATURE_UNIMPLEMENTED
	#define CORE_DISCOVERY_IMPLEMENTATION		CORE_FEATURE_UNIMPLEMENTED
	#define CORE_DYNAMICLIBRARY_IMPLEMENTATION	CORE_FEATURE_UNIMPLEMENTED
	#define CORE_FILESYSTEM_IMPLEMENTATION		CORE_FEATURE_UNIMPLEMENTED

#elif CTL_RTOS

	#define CORE_PLATFORM_DIRECTORY ctlrtos
	#define CORE_ATOMIC_IMPLEMENTATION			CORE_FEATURE_IMPLEMENTATION_POSIX
	#define CORE_SSL_IMPLEMENTATION				CORE_FEATURE_UNIMPLEMENTED
	#define CORE_ATOMIC_STACK_IMPLEMENTATION	CORE_FEATURE_UNIMPLEMENTED
	#define CORE_NETWORK_IMPLEMENTATION			CORE_FEATURE_IMPLEMENTATION_LWIP
	#define CORE_SOCKET_IMPLEMENTATION			CORE_FEATURE_IMPLEMENTATION_LWIP
	#define CORE_DISCOVERY_IMPLEMENTATION		CORE_FEATURE_UNIMPLEMENTED
	#define CORE_INTERPROCESS_IMPLEMENTATION	CORE_FEATURE_UNIMPLEMENTED
	#define CORE_DYNAMICLIBRARY_IMPLEMENTATION	CORE_FEATURE_UNIMPLEMENTED
	#define CORE_FILESYSTEM_IMPLEMENTATION		CORE_EXTERNAL_PLATFORM_IMPLEMENTATION
	#define CORE_DEBUG_IMPLEMENTATION			CORE_EXTERNAL_PLATFORM_IMPLEMENTATION

#elif __ZEPHYR__

	#define CORE_PLATFORM_DIRECTORY zephyr
	#define CORE_ATOMIC_IMPLEMENTATION			CORE_FEATURE_IMPLEMENTATION_POSIX
	#define CORE_SSL_IMPLEMENTATION				CORE_FEATURE_UNIMPLEMENTED
	#define CORE_ATOMIC_STACK_IMPLEMENTATION	CORE_FEATURE_UNIMPLEMENTED
	#define CORE_DISCOVERY_IMPLEMENTATION		CORE_FEATURE_UNIMPLEMENTED
	#define CORE_INTERPROCESS_IMPLEMENTATION	CORE_FEATURE_UNIMPLEMENTED
	#define CORE_DYNAMICLIBRARY_IMPLEMENTATION	CORE_FEATURE_UNIMPLEMENTED
	#define CORE_FILESYSTEM_IMPLEMENTATION		CORE_FEATURE_UNIMPLEMENTED
	#define CORE_NETWORK_IMPLEMENTATION			CORE_FEATURE_UNIMPLEMENTED
	#define CORE_SOCKET_IMPLEMENTATION			CORE_FEATURE_UNIMPLEMENTED

#elif AZURE

	#define CORE_PLATFORM_DIRECTORY azure
	#define CORE_ATOMIC_IMPLEMENTATION			CORE_FEATURE_IMPLEMENTATION_POSIX
	#define CORE_ATOMIC_STACK_IMPLEMENTATION	CORE_FEATURE_IMPLEMENTATION_POSIX
	#define CORE_FILESYSTEM_IMPLEMENTATION		CORE_FEATURE_UNIMPLEMENTED
	#define CORE_DEBUG_IMPLEMENTATION			CORE_FEATURE_IMPLEMENTATION_CMSIS
	#define CORE_SOCKET_IMPLEMENTATION			CORE_FEATURE_UNIMPLEMENTED
	#define CORE_NETWORK_IMPLEMENTATION			CORE_FEATURE_UNIMPLEMENTED
	#define CORE_SSL_IMPLEMENTATION				CORE_FEATURE_UNIMPLEMENTED

#elif CORE_PLATFORM_CMSIS

	#define CORE_TIME_IMPLEMENTATION			CORE_FEATURE_IMPLEMENTATION_CMSIS
	#define CORE_THREAD_IMPLEMENTATION			CORE_FEATURE_IMPLEMENTATION_CMSIS
	#define CORE_ATOMIC_IMPLEMENTATION			CORE_FEATURE_UNIMPLEMENTED
	#define CORE_ATOMIC_STACK_IMPLEMENTATION	CORE_FEATURE_UNIMPLEMENTED
	#define CORE_NETWORK_IMPLEMENTATION			CORE_FEATURE_UNIMPLEMENTED
	#define CORE_SSL_IMPLEMENTATION				CORE_FEATURE_UNIMPLEMENTED
	#define CORE_DISCOVERY_IMPLEMENTATION		CORE_FEATURE_UNIMPLEMENTED
	#define CORE_INTERPROCESS_IMPLEMENTATION	CORE_FEATURE_UNIMPLEMENTED
	#define CORE_DYNAMICLIBRARY_IMPLEMENTATION	CORE_FEATURE_UNIMPLEMENTED
	#define CORE_FILESYSTEM_IMPLEMENTATION		CORE_FEATURE_UNIMPLEMENTED
	#define CORE_DEBUG_IMPLEMENTATION			CORE_FEATURE_IMPLEMENTATION_CMSIS

#elif LITTLEKERNEL

	#define CORE_PLATFORM_DIRECTORY lk
	#define CORE_ATOMIC_IMPLEMENTATION			CORE_FEATURE_IMPLEMENTATION_POSIX
	#define CORE_ATOMIC_STACK_IMPLEMENTATION	CORE_FEATURE_IMPLEMENTATION_POSIX
	#define CORE_FILESYSTEM_IMPLEMENTATION		CORE_FEATURE_UNIMPLEMENTED
	#define CORE_NETWORK_IMPLEMENTATION			CORE_FEATURE_UNIMPLEMENTED
	#define CORE_SOCKET_IMPLEMENTATION			CORE_FEATURE_UNIMPLEMENTED
	#define CORE_SSL_IMPLEMENTATION				CORE_FEATURE_UNIMPLEMENTED

#else
	
	// This is an unknown/external platform. We expect implementations to define CORE_PLATFORM_NAME and add implementation files to the include path.
	#ifndef CORE_PLATFORM_NAME
	#error Unknown platform. Define CORE_PLATFORM_NAME and add core platform implementation directory to include path.
	#endif

#endif

//////////////////////////////////////////////////////////////////////////////////////////////////
// Helper macros for platform-specific includes
//////////////////////////////////////////////////////////////////////////////////////////////////

#define CORE_PLATFORM_INCLUDE_EVALUATOR_(FILEPREFIX,PLATFORMDIR,FILESUFFIX) STRINGIFY (core/PLATFORMDIR/FILEPREFIX.FILESUFFIX.h)

#ifdef CORE_PLATFORM_DIRECTORY
	/** Generate platform-specific include path. */
	#define CORE_PLATFORM_HEADER(FILEPREFIX) CORE_PLATFORM_INCLUDE_EVALUATOR_ (FILEPREFIX, platform/CORE_PLATFORM_DIRECTORY, CORE_PLATFORM_DIRECTORY)

	/** Generate platform-specific include path for implementation classes. */
	#define CORE_PLATFORM_IMPLEMENTATION_HEADER(FILEPREFIX) CORE_PLATFORM_INCLUDE_EVALUATOR_ (FILEPREFIX, platform/CORE_PLATFORM_DIRECTORY, CORE_PLATFORM_DIRECTORY)

	/** Generate platform-specific include path for external implementation classes. */
	#define CORE_EXTERNAL_PLATFORM_IMPLEMENTATION_HEADER(FILEPREFIX) STRINGIFY (FILEPREFIX.CORE_PLATFORM_DIRECTORY.h)
#else
	/** Generate platform-specific include path for external implementation classes. */
	#define CORE_EXTERNAL_PLATFORM_IMPLEMENTATION_HEADER(FILEPREFIX) STRINGIFY (FILEPREFIX.CORE_PLATFORM_NAME.h)		

	/** Generate platform-specific include path for implementation classes in external platform implementation directory. */
	#define CORE_PLATFORM_IMPLEMENTATION_HEADER(FILEPREFIX) CORE_EXTERNAL_PLATFORM_IMPLEMENTATION_HEADER (FILEPREFIX)	
#endif

#endif // _corefeatures_h

