//************************************************************************************************
//
// This file is part of Crystal Class Library (R)
// Copyright (c) 2025 CCL Software Licensing GmbH.
// All Rights Reserved.
//
// Licensed for use under either:
//  1. a Commercial License provided by CCL Software Licensing GmbH, or
//  2. GNU Affero General Public License v3.0 (AGPLv3).
// 
// You must choose and comply with one of the above licensing options.
// For more information, please visit ccl.dev.
//
// Filename    : ccl/extras/tools/argumentparser.h
// Description : Argument parser utility class.
//
//************************************************************************************************

#ifndef _argumentparser_h
#define _argumentparser_h

#include "ccl/base/collections/stringlist.h"

#include "ccl/public/system/iconsole.h"

namespace CCL {

//************************************************************************************************
// Argument
//************************************************************************************************

namespace Argument
{
	/** Argument traits for use with ArgumentParser::add (). */
	enum Flags
	{
		kOptional = 1 << 0, ///< Argument is not required.
		kShiftable = 1 << 1, ///< Argument is not positional.
		kExpectsValue = 1 << 2 ///< Token after the argument is interpreted as the argument's value.
	};
}

//************************************************************************************************
// ArgumentParser
/** Manage argument configuration, resolve arguments from argument list. */
//************************************************************************************************

class ArgumentParser: public Object
{
public:
	/** Flags to control the behavior of ArgumentParser::parse (). */
	enum Flags
	{
		kAllowUnknownArguments = 1 << 0 ///< Don't fail when parsing unknown arguments
	};

	/** Add argument 'name' with 'flags' properties, set 'defaultValue' for optional arguments. */
	void add (StringRef name, StringRef description = nullptr, int flags = 0, VariantRef defaultValue = Variant ());

	/** Add choice argument 'name' allowing one of 'choices', must have 'choices' if shiftable, set 'defaultValue' for optional arguments. */
	void add (StringRef name, const StringList& choices, StringRef description = nullptr, int flags = 0, VariantRef defaultValue = Variant ());

	/** Get parsed value of 'name' argument, returns default value for optional unresolved argument. */
	Variant get (StringRef name) const;

	/** Get a list of all arguments that have not been parsed as named arguments. */
	const StringList& getUnparsedArguments () const;

	/**
	 * Attempt to resolve arguments, run before using 'get ()', safe to rerun.
	 * @returns kResultFailed if argument configuration is invalid, kResultOk or kResultFalse otherwise.
	 */
	tresult parse (ArgsRef argsList, int flags = 0);

	/** Print usage information to the console. */
	void printUsage (System::IConsole& console, StringRef command, StringRef additionalArguments = nullptr);

protected:
	class Description;
	class Result;

	Vector<Description> args; ///< Immutable argument configuration.
	Vector<Result> results; ///< Argument states, created on parse ().
	StringList unparsedArguments; ///< Arguments that have not been parsed as named arguments.

	/** Lookup 'arg' in 'args', store value in 'result' on match. */
	void resolve (Result& result, StringList& args, const Description& arg);
};

//************************************************************************************************
// ArgumentParser::Description
/** Argument parser internal argument description. */
//************************************************************************************************

class ArgumentParser::Description
{
public:
	Description (StringRef name = nullptr, const StringList& choices = {}, StringRef description = nullptr, int flags = 0, VariantRef defaultValue = Variant ());

	PROPERTY_READONLY_FLAG (flags, Argument::kOptional, isOptional)
	PROPERTY_READONLY_FLAG (flags, Argument::kShiftable, isShiftable)
	PROPERTY_READONLY_FLAG (flags, Argument::kExpectsValue, expectsValue)
	PROPERTY_STRING (description, Description)
	PROPERTY_BY_REFERENCE (StringList, choices, Choices)

	String getName () const;
	Variant getDefaultValue () const;
	bool matches (StringRef arg) const;
	bool hasChoices () const;

protected:
	String name; ///< Identifier.
	StringList choices; ///< Allowed values, must not be empty for shiftable args.
	Variant defaultValue; ///< Fallback value for unresolvable, optional args.
	int flags; ///< Argument traits, see Argument::Flags.
};

//************************************************************************************************
// ArgumentParser::Result
/** Argument data generated by parser in correspondence to an argument description. */
//************************************************************************************************

class ArgumentParser::Result
{
public:
	/** Parsed status. */
	enum Status
	{
		kUnresolved, ///< Argument not yet parsed.
		kFound, ///< Parser could resolve argument.
		kNotFound ///< Parser could not resolve argument.
	};

	Result (StringRef name = nullptr);

	PROPERTY_VARIABLE (Variant, value, Value)
	PROPERTY_VARIABLE (Status, status, Status)

	String getName () const;

protected:
	String name; ///< Argument name, identifier.
};

} // namespace CCL

#endif // _argumentparser_h
