include_guard (DIRECTORY) 

set_target_properties(tuioservice PROPERTIES INSTALL_RPATH "$ORIGIN/..;$ORIGIN")

#install (TARGETS tuioservice LIBRARY DESTINATION ${VENDOR_PLUGINS_RUNTIME_DIRECTORY})
#install (TARGETS ${TUIO_LIBRARIES} LIBRARY DESTINATION "${VENDOR_APPLICATION_RUNTIME_DIRECTORY}")

