include_guard (DIRECTORY)

if(${VENDOR_USE_PUBLISHER_CERTIFICATE})
	set_target_properties (jsonconverter PROPERTIES
		XCODE_ATTRIBUTE_CODE_SIGN_STYLE "Manual"
		XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "${SIGNING_CERTIFICATE_MAC}"
	)
endif()