//************************************************************************************************
//
// Bin2C Tool
//
// This file is part of Crystal Class Library (R)
// Copyright (c) 2025 CCL Software Licensing GmbH.
// All Rights Reserved.
//
// Licensed for use under either:
//  1. a Commercial License provided by CCL Software Licensing GmbH, or
//  2. GNU Affero General Public License v3.0 (AGPLv3).
// 
// You must choose and comply with one of the above licensing options.
// For more information, please visit ccl.dev.
//
// Filename    : main.cpp
// Description : Bin2C Tool
//
//************************************************************************************************

#include "bin2c.h"

#include "core/portable/corefile.h"

#include "core/public/coreversion.h"

using namespace Core;
using namespace Portable;

void printhelp (void)
{
	printf ("Bin2C Tool " CORE_AUTHOR_COPYRIGHT "\n");
	printf ("Use 3 arguments: bin2c <bin-file> <out-file> <array_name>\n");
	printf ("\n");
}

#define ARG_FILE			1
#define ARG_OUTFILE			2
#define ARG_ARRAY_NAME		3
#define ARG_NUM				4

int main (int argc, char* argv[])
{
	if(argc < ARG_NUM)
	{
		printhelp ();
		return 0;
	}
	FileStream reader;
	if(!reader.open (argv[ARG_FILE]))
	{
		printf("ERROR: Could not open binary file %s\n", argv[ARG_FILE]);
		return 1;
	}
	int filesize = (int)reader.getFileSize ();
	ASSERT(filesize > 0)
	
	FileUtils::deleteFile (argv[ARG_OUTFILE]);
	
	// create the file
	FileStream writer;
	if(!writer.open (argv[ARG_OUTFILE]))
	{
		if(!writer.create (argv[ARG_OUTFILE]))
		{
			printf("ERROR: Could not open output file:%s\n", argv[ARG_OUTFILE]);
			return 1;
		}
	}

	const int lineW = 32;

	Core::CString256 str (bin2c_commentline);
	str += "// File Generated by Bin2C\n\n";
	writer.writeBytes ((const void*)str.getBuffer (), str.length ());

	bin2c (writer, reader, argv[ARG_ARRAY_NAME], filesize);
	
	writer.close ();
	reader.close ();
	return 0;
}

