include_guard (DIRECTORY)

if (CCL_DISABLE_CPACK)
    return ()
endif ()

set (CPACK_PACKAGE_VENDOR ${apptemplate_COMPANY})
set (CPACK_PACKAGE_CONTACT ${apptemplate_VENDOR_MAIL})
set (CPACK_PACKAGE_NAME "apptemplate")
set (CPACK_DEBIAN_PACKAGE_PROVIDES "apptemplate")
set (CPACK_PACKAGE_DESCRIPTION_SUMMARY "Application Description")
set (CPACK_PACKAGE_VERSION_MAJOR ${apptemplate_VERSION_MAJOR})
set (CPACK_PACKAGE_VERSION_MINOR ${apptemplate_VERSION_MINOR})
set (CPACK_PACKAGE_VERSION_PATCH ${apptemplate_VERSION_REVISION})
set (CPACK_PACKAGE_VERSION "${apptemplate_VERSION_MAJOR}.${apptemplate_VERSION_MINOR}.${apptemplate_VERSION_REVISION}.${apptemplate_VERSION_BUILD}")
set (CPACK_RESOURCE_FILE_LICENSE "${CCL_IDENTITIES_DIR}/ccl/eula/EULA.txt")
#set (CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")

set (CPACK_GENERATOR "DEB")

set (CPACK_DEBIAN_PACKAGE_SECTION "utils")
set (CPACK_PACKAGE_HOMEPAGE_URL ${apptemplate_WEBSITE})

set (CPACK_PACKAGE_FILE_NAME "${VENDOR_PRODUCT_NAME}-${VENDOR_TARGET_ARCHITECTURE}")

include (CPack)
